name: Run tests and deploy to Elastic Beanstalk

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
env:
  APPLICATION_NAME: lol-insights-backend
  ENVIRONMENT_NAME: Lolinsightsbackend-env
  AWS_REGION: eu-west-1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Run tests
        run: mvn test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Build and package
        run: mvn --batch-mode --update-snapshots verify

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: jar-package
          path: target/*.jar
          retention-days: 1


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Download build artifact
        uses: actions/download-artifact@v2
        id: download
        with:
          name: jar-package

      - name: Zip deployment package
        run: zip -r deploy.zip *.jar .elasticbeanstalk

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ env.APPLICATION_NAME }}
          environment_name: ${{ env.ENVIRONMENT_NAME }}
          version_label: v1-${{ github.sha }}
          region: ${{ env.AWS_REGION }}
          deployment_package: deploy.zip