name: Run tests

on:
    pull_request:
        branches: ["main"]
    push:
        branches: ["main"]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Setup Java 11
              uses: actions/setup-java@v3
              with:
                  distribution: "zulu"
                  java-version: "11"

            - name: Run tests
              run: mvn test
